package blog.model;

import java.util.Date;


public class BlogPosts {
	protected int postId;
	protected String title;
	protected String picture;
	protected String content;
	protected boolean published;
	protected Date created;
	protected BlogUsers blogUser;
	
	// This constructor can be used for reading records from MySQL, where we have all fields,
	// including the PostId.
	public BlogPosts(int postId, String title, String picture, String content,
			boolean published, Date created, BlogUsers blogUser) {
		this.postId = postId;
		this.title = title;
		this.picture = picture;
		this.content = content;
		this.published = published;
		this.created = created;
		this.blogUser = blogUser;
	}
	
	// This constructor can be used for reading records from MySQL, where we only have the postId,
	// such as a foreign key reference to PostId.
	// Given PostId, we can fetch the full BlogPost record.
	public BlogPosts(int postId) {
		this.postId = postId;
	}
	
	// This constructor can be used for creating new records, where the postId may not be
	// assigned yet since it is auto-generated by MySQL.
	public BlogPosts(String title, String picture, String content,
			boolean published, Date created, BlogUsers blogUser) {
		this.title = title;
		this.picture = picture;
		this.content = content;
		this.published = published;
		this.created = created;
		this.blogUser = blogUser;
	}

	public int getPostId() {
		return postId;
	}

	public void setPostId(int postId) {
		this.postId = postId;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getPicture() {
		return picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public boolean isPublished() {
		return published;
	}

	public void setPublished(boolean published) {
		this.published = published;
	}

	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public BlogUsers getBlogUser() {
		return blogUser;
	}

	public void setBlogUser(BlogUsers blogUser) {
		this.blogUser = blogUser;
	}
}